version: 2

models:
  - name: int_anc_vs_delivery
    columns:
      - name: state_name
        tests:
          - not_null
      - name: survey_year
        tests:
          - not_null

  - name: int_neonatal_mortality
    columns:
      - name: state_name
        tests:
          - not_null
      - name: survey_year
        tests:
          - not_null

  - name: int_conflict_intensity
    columns:
      - name: state_name
        tests:
          - not_null
      - name: event_year
        tests:
          - not_null

  - name: int_dhs_delta
    columns:
      - name: state_name
        tests:
          - unique
          - not_null
    
  - name: int_wealth_delivery
    columns:
      - name: state_name
        tests: 
          - not_null
      - name: survey_year
        tests:
          - not_null
      - name: wealth_index
        tests:
          - not_null
      