version: 2

models:
  - name: mart_state_health_profile
    columns:
      - name: state_name
        tests:
          - not_null
      - name: survey_year
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - state_name
            - survey_year
  
  - name: mart_conflict_vs_health
    columns:
      - name: state_name
        tests:
          - not_null
      - name: survey_year
        tests:
          - not_null